from collections.abc import Mapping
from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from .pipelines import PipelineSpec


class MLflowBackend(Protocol):
    def create_experiment(self, name: str) -> str: ...
    def get_run(self, run_id: str) -> Mapping[str, object]: ...
    def start_run(self, experiment_id: str, name: str) -> str: ...
    def end_run(self, run_id: str, status: str) -> None: ...
    async def get_run_async(self, run_id: str) -> Mapping[str, object]: ...
    async def aclose(self) -> None: ...


class PipelineExecutor(Protocol):
    name: str

    def execute(self, pipeline: "PipelineSpec") -> str: ...

